# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_pcbbinom <- function(q, size, alpha, beta, lower_tail, log_p, prec) {
    .Call(`_cbbinom_cpp_pcbbinom`, q, size, alpha, beta, lower_tail, log_p, prec)
}

cpp_qcbbinom <- function(p, size, alpha, beta, lower_tail, log_p, prec, tol, max_iter) {
    .Call(`_cbbinom_cpp_qcbbinom`, p, size, alpha, beta, lower_tail, log_p, prec, tol, max_iter)
}

cpp_dcbbinom <- function(x, size, alpha, beta, log, prec) {
    .Call(`_cbbinom_cpp_dcbbinom`, x, size, alpha, beta, log, prec)
}

cpp_rcbbinom <- function(n, size, alpha, beta, prec, tol, max_iter) {
    .Call(`_cbbinom_cpp_rcbbinom`, n, size, alpha, beta, prec, tol, max_iter)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_cbbinom_RcppExport_registerCCallable`)
})
