# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_pcbbinom <- function(q, size, alpha, beta, lower_tail, log_p, tol, max_iter, prec) {
    .Call(`_cbbinom_cpp_pcbbinom`, q, size, alpha, beta, lower_tail, log_p, tol, max_iter, prec)
}

cpp_qcbbinom <- function(p, size, alpha, beta, lower_tail, log_p, p_tol, p_max_iter, p_prec, root_tol, root_max_iter) {
    .Call(`_cbbinom_cpp_qcbbinom`, p, size, alpha, beta, lower_tail, log_p, p_tol, p_max_iter, p_prec, root_tol, root_max_iter)
}

cpp_dcbbinom <- function(x, size, alpha, beta, log, tol, max_iter, prec) {
    .Call(`_cbbinom_cpp_dcbbinom`, x, size, alpha, beta, log, tol, max_iter, prec)
}

cpp_rcbbinom <- function(n, size, alpha, beta, p_tol, p_max_iter, p_prec, root_tol, root_max_iter) {
    .Call(`_cbbinom_cpp_rcbbinom`, n, size, alpha, beta, p_tol, p_max_iter, p_prec, root_tol, root_max_iter)
}

#' Generalized hypergeometric function
#'
#' \code{gen_hypergeo} computes generalized hypergeometric function.
#'
#' @param U,L Numeric vectors for upper and lower values.
#' @param x Numeric (1L) as common ratio.
#' @param tol \code{NULL} or Numeric (1L) as convergence tolerance.
#' If \code{NULL}, use the epsilon for the \code{value_type} determined by
#' \code{boost::math::tools::promote_args} (e.g. for \code{double} input,
#' usually use the epsilon for \code{long double}).
#' @param max_iter Integer (1L) as iteration limit.
#' @param prec Numeric (1L) as precision level (0/20/50/100/200) during computation,
#' a.k.a the number of precise digits defined in \code{boost::multiprecision::cpp_bin_float}.
#' For level 0, \code{double} precision is used. For level 20, the precision is slightly
#' higher than \code{long double}
#' (\code{.Machine[["longdouble.eps"]] = `r format(.Machine[["longdouble.eps"]], scientific = TRUE)`}).
#' For higher levels of 50/100/200, the higher the precision, the slower the computation.
#' For prec < 20, use level 0; for 20 <= prec < 50, use level 20; for 50 <= prec < 100,
#' use level 50; for 100 <= prec < 200, use level 100; for prec >= 200, use level 200.
#' @param check_mode Logical (1L) indicating whether the mode of \code{x}
#' should be checked for obvious convergence failures.
#' @param log Logical (1L) indicating whether result is given as log(result).
#'
#' @return Numeric (1L) as the result of computation (at \code{double} precision).
#' Warnings are issued if failing to converge.
#'
#' @note Change log:
#' \itemize{
#'   \item{0.1.0 Xiurui Zhu - Initiate the function.}
#'   \item{0.1.1 Xiurui Zhu - Use \code{boost} for higher accuracy.}
#' }
#' @author Xiurui Zhu
#'
#' @export
#'
#' @examples
#' gen_hypergeo(U = c(1.1, 0.2, 0.3), L = c(10.1, 4 * pi), x = 1,
#'              tol = NULL, max_iter = 10000L, prec = 20, check_mode = TRUE, log = FALSE)
gen_hypergeo <- function(U, L, x, tol, max_iter, prec, check_mode, log) {
    .Call(`_cbbinom_gen_hypergeo`, U, L, x, tol, max_iter, prec, check_mode, log)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_cbbinom_RcppExport_registerCCallable`)
})
